- name: Remove Directory
  ansible.builtin.file:
    path: "{{ APP_LOC }}"
    state:  absent

- name: Remove Directory
  ansible.builtin.file:
    path: "{{ APP_LOC }}"
    state:  present

- name: Download url
  ansible.builtin.unarchive:
    src:  "https://expense-builds.s3.us-east-1.amazonaws.com/expense-{{ COMPONENT }}-v2.zip"
    dest: "{{ APP_LOC }}"
    remote_src: yes