- name: Install MySql Libraries
  ansible.builtin.pip:
    name: PyMySQL
    executable: pip3.9
- name: "Install MySQL"
  ansible.builtin.package:
    name: mysql-server
    state:  installed
- name: "Start and Enable MySQL"
  ansible.builtin.service:
    name: mysqld
    state:  started
    enabled:  yes
- name: Connect to sql-server
  community.mysql.mysql_info:
    login_user: root
    login_password: "{{ lookup('amazon.aws.aws_ssm', '/expense/mysql/mysqlpw', decrypt=true ) }}"
    login_host: "172.31.27.46"
  register: "mysql_infom"
  ignore_errors: true
- name: Print output
  ansible.builtin.debug:
    msg:  "{{ mysql_infom }}"
- name: set login_password
  ansible.builtin.command:  mysql_secure_installation --set-root-pass {{ mysql_root_pw }}
  when: mysql_infom.failed is true